- src/ngx_stream_lua_socket_tcp.c
[src/ngx_stream_lua_socket_tcp.c:1173]: (warning) Logical conjunction always evaluates to false: n < 1 && n > 4.
> cppcheck issue

- src/ngx_stream_lua_balancer.c
- t/138-balancer.t
> synced to meta-lua-nginx-module #18222ed for balancer status code

- src/ngx_stream_lua_request.c
- src/ngx_stream_lua_util.h
- t/058-tcp-socket.t
- t/087-udp-socket.t
non-Lua, cleanup hooks will be incorrectly skipped. #4d0361f
Changes were generated from https://github.com/openresty/meta-lua-nginx-module/pull/9.
To reproduce, simply run the added test without this PR using no-pool NGINX.
`stream` subsystem does not support cleanup handler natively, so we added emulation for such functionality inside `stream_lua`. However, those cleanup handlers will only be executed if "request" is terminated using `ngx_stream_lua_finalize_real_request()`. Since this function is `stream_lua` specific, content phase handlers like the built-in `return` directive will **not** execute those cleanup hooks.
Later on when the `__gc` metamethod on the cosocket udata is executed in another "request", it will attempt to dereference the old "request" which would have been freed …
> bugfix: when only Lua preread handler is present and content handler is

- README.md
Add two missing links in README.
> doc: fix missing link of ssl_certby_lua*

- src/ngx_stream_lua_util.c
- t/157-global-var.t
* more appropriate message ("writing" instead of "attempting to")
* remove http/lua prefix (`ngx.log` will inject `[lua]` and `stream [lua]`
already)
* remove unused cached global
* cache `tostring` global locally
* updated tests
> misc: updated _G write guard message to be more accurate.

- .travis.yml
This allows the `t/ssl-*.t` test suites to run. Prior to this commit,
they are skipped with:
> too old OpenSSL, need 1.0.2e, was 1.0.1f 6 Jan 2014
See: https://travis-ci.org/openresty/stream-lua-nginx-module/jobs/449697573
Fix #129
> chore: travis: ensure ssl_certby test suites run on Travis-CI

- src/ngx_stream_lua_module.c
luajit is detected since many optimizations would be missing.
> change: we now print an alert when a non openresty-specific version of

- src/ngx_stream_lua_common.h
- src/ngx_stream_lua_module.c
- src/ngx_stream_lua_util.h
bugfix: the lightuserdata mask was broken in WIN64.
bugfix: we now only apply the lightuserdata mask on platforms that are at least 64bits.
bugfix: the 'dd' calls in ngx_subsys_lua_util.h are now guarded by '#ifdef DDEBUG'.
> synchronized to meta-lua-nginx-module #b7267fc

- README.md
ssl_certificate_by_lua_block has been implemented in lastest stream_lua，so we should remove it from TODO.
> doc: remove ssl_cert in TODO

- config
Follow-up commit to 5a97ccef705c07f7d1784a1887b90bbc4c0a8010
> bugfix: ensured the 'pcre_version' symbol is also preserved on Darwin platforms.

- src/ngx_stream_lua_ssl_certby.c
- t/140-ssl-c-api.t
This PR adds a FFI interface that allows users to configure SSL client certificate verification dynamically. For example, Nginx can now read SNI first and then determine whether to request a client certificate during handshake. Optionally, caller can pass in a CA list used for verification.
See https://github.com/openresty/meta-lua-nginx-module/pull/75 .
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.
> feature: add FFI interface to verify SSL client certificate

- src/api/ngx_stream_lua_api.h
- src/ngx_stream_lua_api.c
As the req_type in stream subsystem is unexported.
Fix https://github.com/openresty/stream-lua-nginx-module/issues/180.
> bugfix: hide get_request API in stream subsystem

- src/ngx_stream_lua_logby.c
If turn on nginx debug log `./configure --with-debug ...`, but not select `debug_http` log level. 
ngx_log_debug1(NGX_LOG_DEBUG_HTTP, ...) will be ignored, malloc_trim() can't be executed as function parameter.
And memory isn't returned to OS immediately. This bug may cause serious memory leak, OOM.
Simply,  `ngx_log_debug1` is optional, but `malloc_trim` obligatory.
> bugfix: memory leak in debug log function

- src/ngx_stream_lua_socket_udp.c
- t/142-req-udp-socket.t
sync with meta-lua-nginx-module e1f1f20.
https://github.com/openresty/meta-lua-nginx-module/pull/82
> bugfix: ignore the `raw` argument when acquiring UDP request socket.

- src/ngx_stream_lua_timer.c
```
785    buf = p;
786
deref_ptr: Directly dereferencing pointer c.
787    if (c->addr_text.len) {
788        p = ngx_snprintf(buf, len, ", client: %V", &c->addr_text);
789        len -= p - buf;
790        buf = p;
791    }
792
CID 251610 (#1 of 1): Dereference before null check (REVERSE_INULL)check_after_deref: Null-checking c suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
793    if (c && c->listening && c->listening->addr_text.len) {
794        p = ngx_snprintf(buf, len, ", server: %V", &c->listening->addr_text);
795        /* len -= p - buf; */
796        buf = p;
797    }
```
> chore: fix possible null pointer dereference found by Coverity

- src/ngx_stream_lua_util.c
If the worker voluntary enter into graceful shutdown state, the master will not respawn worker with the same worker id until the worker exit.
when reuseport is on, the new connections assigned to the voluntary graceful shutdown worker will not be accepted.
when reuseport is off, the new connections will be accepted by other processes which are still working. But if all workers are in voluntary shutdown state, the new connections will not be accepted.
So the worker should not enter into the voluntary graceful shutdown state when LUA_ERRMEM occurs.
> change: changed from graceful shutdown to abort when lua_resume return LUA_ERRMEM.

- src/ngx_stream_lua_coroutine.c
- t/139-ssl-cert-by.t
calling coroutine APIs in the preread and ssl_cert phase will return abnormal results
> bugfix: old coroutine APIs were used in the preread and ssl_cert phase

- src/ngx_stream_lua_initworkerby.c
- t/124-init-worker.t
should use the top lua conf top_llcf for init_worker block.
also renamed the variables from `*lcf` to `*scf`.
> bugfix: some lua configurations (i.e. `lua_ssl_trusted_certificate`) were missing in the init_worker phase.

- src/ngx_stream_lua_ssl_certby.c
It leads to 'error: ‘ngx_stream_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]'
error.
> bugfix: we didn't exclude the ssl_verify_callback when compiling with LibreSSL

- src/ngx_stream_lua_regex.c
- t/120-re-find.t
lua_regex_match_limit takes effect globally for all regexes used in ngx.re
api. However, the match_limit field of pcre_extra block is not supported in
pcre_dfa_exec()(so does match_limit_recursion), because it is meaningless
in DFA matching. And pcre_dfa_exec() will return -18(PCRE_ERROR_DFA_UMLIMIT)
when the directive is used. Here we just ignore the directive in DFA mode.
> bugfix: we should ignore match limit in DFA mode.

- src/ngx_stream_lua_shdict.c
- t/043-shdict.t
修复一个share dict list过期处理的问题：
当向一个过期的list push时，
如果过期的list没有被清除，重新复用时，list长度没有重新置为0，导致新队列pop时，触发错误
例子：
local dogs = ngx.shared.dogs
dogs:lpush("cc", "1")
dogs:lpush("aa", "1")
dogs:expire("aa", 0.2)
ngx.sleep(0.3)
dogs:lpush("aa", "2")
dogs:lpop("aa")
dogs:lpop("aa") --此时触发错误，而不是期望的返回nil
> bugfix:fix expired(not cleared)share dict list len incorrect problem

- t/068-socket-keepalive.t
to pass the test case in valgrind + mockeagain mode.
> tests: t/068-socket-keepalive.t: set the connection timeout to 100 ms.

- README.md
- src/ngx_stream_lua_common.h
- src/ngx_stream_lua_module.c
- t/163-ssl-two-verification.t
Support lua_ssl_certificate and lua_ssl_certificate_key，these 2 directives are used for ssl two-way verification
> feature: Support lua_ssl_certificate and lua_ssl_certificate_key

- src/ngx_stream_lua_common.h
pcre.h is a PCRE header and is not exposed by PCRE2 library causing compilation error as the header is not found.
Don't include pcre.h if nginx is compiled with PCRE2 support enabled.
Fixes: 08841a243f1a ("feature: support pcre2")
> bugfix: don't include pcre.h with PCRE2 used

- src/ngx_stream_lua_socket_tcp.c
- t/058-tcp-socket.t
Can be reproduced by following example:
```
user www-data;
daemon off;
master_process off;
events {
}
stream {
error_log /dev/stdout info;
server {
listen 23333;
content_by_lua_block {
local t = ngx.socket.tcp()
t:shutdown("send")
}
}
}
```
This PR moves the check of `u` before calling `ngx_stream_lua_socket_handle_write_error`.
> bugfix: correctly error out when ngx.socket.tcp is shutdown before connect

- config
Since the C API ngx_stream_lua_pcre_version was introduced in this module, and Lua FFI no longer directly calls pcre_version, issue #168 is no longer necessary.
> changes: remove the useless pcre config

- src/ngx_stream_lua_regex.c
Also update the name of `ovecsize` in `ngx_http_lua_ffi_exec_regex` to reflect the difference.
> bugfix: correct offset vector memory allocation size for PCRE2.

- src/ngx_stream_lua_module.c
- src/ngx_stream_lua_ssl_certby.c
Check for ssl context as in http lua module instead of a field removed in https://hg.nginx.org/nginx/rev/e28b044908cb.
> bugfix: fixed failure to build from source with nginx 1.25.5+

- src/ngx_stream_lua_socket_tcp.c
- t/129-ssl-socket.t
Go to https://github.com/openresty/lua-nginx-module/pull/2347 for more details.
> bugfix: fixed keepalive error in cosocket.

- src/ngx_stream_lua_socket_tcp.c
- t/058-tcp-socket.t
porting https://github.com/openresty/lua-nginx-module/pull/2356
When TLSv1.3 is used, the server may send a NewSessionTicket message after the handshake. While this message is ssl-layer data, `tcpsock:sslhandshake` does not consume it.
In the implementation of `setkeepalive`, `recv` is used to confirm the connection is still open and there is no unread data in the buffer. But it treats the NewSessionTicket message as application layer data and then `setkeepalive` fails with this error `connection in dubious state`.
In fact we don't need to peek here, because if the application data is read successfully then the connection is going to be closed anyway. Therefore, `c->recv` can be used instead which will consume the ssl-layer data implicitly.
> bugfix: `setkeepalive` failure on TLSv1.3
