openresty/stream-lua-nginx-module

src/ngx_stream_lua_control.c, src/ngx_stream_lua_directive.c, src/ngx_stream_lua_misc.c, src/ngx_stream_lua_regex.c, src/ngx_stream_lua_script.c, src/ngx_stream_lua_semaphore.c, src/ngx_stream_lua_shdict.c, src/ngx_stream_lua_socket_tcp.c, src/ngx_stream_lua_socket_tcp.h, src/ngx_stream_lua_socket_udp.c, src/ngx_stream_lua_timer.c, src/ngx_stream_lua_uthread.c, src/ngx_stream_lua_util.c
checked by ngx-style: https://github.com/openresty/nginx-devel-utils/pull/6
=> style fix: variable name should align with the previous line

t/119-config-prefix.t
I found a test case forgot to convert to stream ; )
Maybe we need an unrelated tool for testing the stream module with ngx_http_lua in test-nginx ?
=> convert test case 119-config-prefix.t to ngx_stream_lua

README.md, src/ngx_stream_lua_common.h, src/ngx_stream_lua_socket_tcp.c, src/ngx_stream_lua_socket_udp.c
That includes documentation improvements and Clang compilation warnings fix.
Closes #78.
=> Updating master to the latest.

README.md, src/ngx_stream_lua_directive.c, src/ngx_stream_lua_directive.h, src/ngx_stream_lua_module.c, t/139-add-variable.t
variables that can be used by both Lua and C code. #46d779b
=> feature: new directive lua_add_variable to allow adding changeable

README.md, src/ngx_stream_lua_common.h, src/ngx_stream_lua_module.c, src/ngx_stream_lua_prereadby.c, t/023-preread/sanity.t, util/build.sh
Changes were generated from https://github.com/openresty/meta-lua-nginx-module/pull/7.
=> feature: added the preread handler postpone feature. #acc4b14c

config, src/ddebug.h, src/ngx_stream_lua_common.h, src/ngx_stream_lua_initworkerby.c, src/ngx_stream_lua_module.c, src/ngx_stream_lua_probe.h, src/ngx_stream_lua_regex.c, src/ngx_stream_lua_semaphore.c, src/ngx_stream_lua_semaphore.h, src/ngx_stream_lua_util.h
Changes are generated from: https://github.com/openresty/meta-lua-nginx-module/pull/37.
lua-resty-core PR: https://github.com/openresty/lua-resty-core/pull/185
=> feature: ngx.semaphore support for stream_lua. #4a1db75

src/ngx_stream_lua_shdict.c
Related PRs:
* https://github.com/openresty/lua-resty-core/pull/196
* https://github.com/openresty/meta-lua-nginx-module/pull/44
=> shdict: enabled FFI support. #bdbaa95

t/140-ssl-c-api.t
=> tests: updated the way to get ngx request in test file.

README.md, config, src/ngx_stream_lua_common.h, src/ngx_stream_lua_directive.c, src/ngx_stream_lua_directive.h, src/ngx_stream_lua_log.c, src/ngx_stream_lua_log.h, src/ngx_stream_lua_log_ringbuf.c, src/ngx_stream_lua_log_ringbuf.h, src/ngx_stream_lua_module.c
* Generated from: https://github.com/openresty/meta-lua-nginx-module/pull/48
* See also: https://github.com/openresty/lua-resty-core/pull/208
=> errlog: enabled FFI support.

README.md, src/ngx_stream_lua_common.h, src/ngx_stream_lua_prereadby.c, src/ngx_stream_lua_socket_tcp.c, src/ngx_stream_lua_socket_tcp.h, t/023-preread/req-socket.t, t/062-count.t
Changes were generated from: https://github.com/openresty/meta-lua-nginx-module/pull/62
=> feature: stream preread peek() method. #7171663

t/023-preread/req-socket.t
This fixes https://travis-ci.org/thibaultcha/stream-lua-nginx-module/jobs/486236998.
=> test: fixed preread ssl test failure in newer version of NGINX core.

.travis.yml, t/139-ssl-cert-by.t
> I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.
Sister PRs:
- https://github.com/openresty/openresty/pull/503
- https://github.com/openresty/no-pool-nginx/pull/8
=> change: upgraded the NGINX core to 1.17.1

src/ngx_stream_lua_contentby.c, src/ngx_stream_lua_socket_tcp.c
=> bugfix: the stream subsystem was built incorrectly in debug mode.

src/ngx_stream_lua_ctx.c
Sync from https://github.com/openresty/meta-lua-nginx-module/pull/83
=> bugfix: added missing SSL feature macro

valgrind.suppress
=> tests: more general supress condiction for ngx_stream_lua_socket_udp_send.

src/ngx_stream_lua_shdict.c, src/ngx_stream_lua_shdict.h
This is the workaround for luajit FFI working on apple silicon.
See:
https://github.com/openresty/lua-nginx-module/issues/2030
https://github.com/LuaJIT/LuaJIT/issues/205
Sister PR:
https://github.com/openresty/lua-resty-core/pull/391
https://github.com/openresty/lua-nginx-module/pull/2037
=> bugfix: Apple silicon workaround

t/058-tcp-socket.t, t/128-duplex-tcp-socket.t
This change relies on this PR:
https://github.com/openresty/test-nginx/pull/151
=> tests: use random port in tcp_listen section.

t/062-count.t
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> tests: fix broken worker API count test

src/ngx_stream_lua_control.c, src/ngx_stream_lua_coroutine.c, src/ngx_stream_lua_semaphore.c, src/ngx_stream_lua_sleep.c, src/ngx_stream_lua_socket_tcp.c, src/ngx_stream_lua_socket_udp.c, src/ngx_stream_lua_uthread.c, src/ngx_stream_lua_util.h
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> feature: add CONTEXT_YIELDABLE constant to stream subsys

.travis.yml, util/build.sh, util/ver-ge
https://github.com/openresty/openresty/pull/920
=> new: upgrade nginx core to 1.25.1

src/ngx_stream_lua_common.h, src/ngx_stream_lua_pcrefix.c, src/ngx_stream_lua_pcrefix.h, src/ngx_stream_lua_regex.c
I hereby granted the copyright of the changes in this pull request
to the authors of this stream-lua-nginx-module project.
=> optimize: make the use of NGX_PCRE2 clearer

src/ngx_stream_lua_ssl_certby.c, t/140-ssl-c-api.t
add ngx_stream_lua_ffi_ssl_client_random function
=> feature: add ngx_stream_lua_ffi_ssl_client_random.
